FROM opengc/opengc

# Clone pytorch
RUN git clone --recursive https://github.com/pytorch/pytorch
# if you are updating an existing checkout
RUN git submodule sync
RUN git submodule update --init --recursive

WORKDIR /root/pytorch

